add_executable(profile_get_canonical profile_get_canonical.cc)
add_executable(test_adminusers test_adminusers.cc)
add_executable(test_buffer test_buffer.cc)
add_executable(test_config test_config.cc)
add_executable(test_config_include test_config_include.cc)
add_executable(test_config_legacy_section test_config_legacy_section.cc)
add_executable(test_config2 test_config2.cc)
add_executable(test_event test_event.cc)
add_executable(test_filter test_filter.cc)
add_executable(test_hint test_hint.cc)
add_executable(test_http test_http.cc)
add_executable(test_json test_json.cc)
add_executable(test_local_address test_local_address.cc)
add_executable(test_log test_log.cc)
add_executable(test_logorder test_logorder.cc)
add_executable(test_logthrottling test_logthrottling.cc)
add_executable(test_percona_proxy_pcre2 test_percona_proxy_pcre2.cc)
add_executable(test_modulecmd test_modulecmd.cc)
add_executable(test_modutil test_modutil.cc)
add_executable(test_monitor test_monitor.cc)
add_executable(test_poll test_poll.cc)
add_executable(test_server test_server.cc)
add_executable(test_service test_service.cc)
add_executable(test_users test_users.cc)
add_executable(test_utils test_utils.cc)

target_link_libraries(profile_get_canonical percona-proxy-common)
target_link_libraries(test_adminusers percona-proxy-common)
target_link_libraries(test_buffer percona-proxy-common)
target_link_libraries(test_config percona-proxy-common)
target_link_libraries(test_config_include percona-proxy-common)
target_link_libraries(test_config_legacy_section percona-proxy-common)
target_link_libraries(test_config2 percona-proxy-common)
target_link_libraries(test_event percona-proxy-common)
target_link_libraries(test_filter percona-proxy-common)
target_link_libraries(test_hint percona-proxy-common)
target_link_libraries(test_http percona-proxy-common)
target_link_libraries(test_json percona-proxy-common)
target_link_libraries(test_local_address percona-proxy-common)
target_link_libraries(test_log percona-proxy-common)
target_link_libraries(test_logorder percona-proxy-common)
target_link_libraries(test_logthrottling percona-proxy-common)
target_link_libraries(test_percona_proxy_pcre2 percona-proxy-common)
target_link_libraries(test_modulecmd percona-proxy-common)
target_link_libraries(test_modutil percona-proxy-common)
target_link_libraries(test_monitor percona-proxy-common)
target_link_libraries(test_poll percona-proxy-common)
target_link_libraries(test_server percona-proxy-common)
target_link_libraries(test_service percona-proxy-common)
target_link_libraries(test_users percona-proxy-common)
target_link_libraries(test_utils percona-proxy-common)

add_test(test_buffer test_buffer)
add_test(test_config test_config)
add_test(test_config_include test_config_include)
add_test(test_config_legacy_section test_config_legacy_section)
add_test(test_config2 test_config2)
add_test(test_event test_event)
add_test(test_filter test_filter)
add_test(test_hint test_hint)
add_test(test_http test_http)
add_test(test_json test_json)
add_test(test_log test_log)
add_test(NAME test_logorder COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/logorder.sh  200 0 1000 ${CMAKE_CURRENT_BINARY_DIR}/logorder.log)
add_test(test_logthrottling test_logthrottling)
add_test(NAME test_percona-proxy-passwd COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/test_percona-proxy-passwd.sh)
add_test(test_percona_proxy_pcre2 test_percona_proxy_pcre2)
add_test(test_modulecmd test_modulecmd)
add_test(test_modutil test_modutil)
add_test(test_monitor test_monitor)
add_test(test_poll test_poll)
add_test(test_server test_server)
add_test(test_service test_service)
add_test(test_utils test_utils)

add_subdirectory(rest-api)
# GCC 10 has a broken ASAN implementation that got fixed in GCC 11. The
# --as-needed flag breaks the crypt and crypt_r interceptors in ASAN and the
# tests that use it must disble the feature that breaks it. For Debian, adding
# --no-as-needed would fix it but for SLES 15 with GCC 11 it still ends up
# failing. To make life simpler, just skip these tests if ASAN is enabled on
# those systems
# TODO: This might not be a false positive, figure out the root cause
if (WITH_ASAN
    AND ${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER 10.0.0
    AND ${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS 12.0.0)
  message(STATUS "Skipping test_adminusers and test_users due to broken ASAN implementation")
else()
  add_test(test_adminusers test_adminusers)
  add_test(test_users test_users)
endif()
