# Check which init.d script to install
find_file(RPM_FNC functions PATHS /etc/rc.d/init.d)
find_file(DEB_FNC init-functions PATHS /lib/lsb)
find_file(SLES_FNC SuSE-release PATHS /etc)

if(EXISTS ${RPM_FNC})
  set(USE_RPM TRUE CACHE BOOL "If init.d script uses /lib/lsb/init-functions instead of /etc/rc.d/init.d/functions.")
elseif(EXISTS ${SLES_FNC})
  set(USE_SLES TRUE CACHE BOOL "SLES11 has reduced /lib/lsb/init-functions and needs a special init-script")
elseif(EXISTS ${DEB_FNC})
  set(USE_DEB TRUE CACHE BOOL "If init.d script uses /lib/lsb/init-functions instead of /etc/rc.d/init.d/functions.")
else()
  message(STATUS "Cannot find required init-functions in /lib/lsb/ or /etc/rc.d/init.d/, will not install init scripts.")
endif()

if(USE_DEB)
  configure_file(${CMAKE_SOURCE_DIR}/etc/ubuntu/init.d/percona-proxy.in ${CMAKE_BINARY_DIR}/percona-proxy @ONLY)
elseif(USE_RPM)
  configure_file(${CMAKE_SOURCE_DIR}/etc/init.d/percona-proxy.in ${CMAKE_BINARY_DIR}/percona-proxy @ONLY)
elseif(USE_SLES)
  configure_file(${CMAKE_SOURCE_DIR}/etc/sles11/init.d/percona-proxy.in ${CMAKE_BINARY_DIR}/percona-proxy @ONLY)
else()
  # Use a dummy file that tells the user that init scripts aren't supported on this platform
  configure_file(${CMAKE_SOURCE_DIR}/etc/fallback/percona-proxy.in ${CMAKE_BINARY_DIR}/percona-proxy @ONLY)
endif()

configure_file(${CMAKE_SOURCE_DIR}/etc/percona-proxy.conf.in ${CMAKE_BINARY_DIR}/percona-proxy.conf @ONLY)

# The systemd service file
if (CMAKE_BUILD_TYPE MATCHES "(D|d)(E|e)(B|b)(U|u)(G|g)")
  # Options enabled only in debug builds (a literal multi-line string)
  set(SERVICE_FILE_DEBUG_OPTIONS "LimitCORE=infinity")
endif()

if (WITH_VALGRIND)
  # For builds that invoke valgrind automatically, use the custom service file.
  configure_file(${CMAKE_SOURCE_DIR}/etc/percona-proxy-valgrind.service.in ${CMAKE_BINARY_DIR}/percona-proxy.service @ONLY)
else()
  configure_file(${CMAKE_SOURCE_DIR}/etc/percona-proxy.service.in ${CMAKE_BINARY_DIR}/percona-proxy.service @ONLY)
endif()

if(PACKAGE)
  message(STATUS "percona-proxy.conf will unpack to: /etc/ld.so.conf.d")
  message(STATUS "startup scripts will unpack to to: /etc/init.d")
  message(STATUS "systemd service files will unpack to to: /usr/lib/systemd/system")
  message(STATUS "upstart files will unpack to: /etc/init/")
  install_file(${CMAKE_BINARY_DIR}/percona-proxy core)
  install_file(${CMAKE_BINARY_DIR}/percona-proxy.conf core)
  install_file(${CMAKE_BINARY_DIR}/percona-proxy.service core)
  install_file(${CMAKE_BINARY_DIR}/upstart/percona-proxy.conf core)
else()
  install(PROGRAMS ${CMAKE_BINARY_DIR}/percona-proxy DESTINATION /etc/init.d COMPONENT core)
  install(FILES ${CMAKE_BINARY_DIR}/percona-proxy.conf  DESTINATION /etc/ld.so.conf.d COMPONENT core)
  install(FILES ${CMAKE_BINARY_DIR}/percona-proxy.service  DESTINATION /usr/lib/systemd/system COMPONENT core)
  install(FILES ${CMAKE_BINARY_DIR}/upstart/percona-proxy.conf DESTINATION /etc/init/)
  install(FILES ${CMAKE_SOURCE_DIR}/etc/logrotate.d/percona-proxy-logrotate DESTINATION /etc/logrotate.d/)
  message(STATUS "Installing percona-proxy.conf to: /etc/ld.so.conf.d")
  message(STATUS "Installing startup scripts to: /etc/init.d")
  message(STATUS "Installing systemd service files to: /usr/lib/systemd/system")
  message(STATUS "Installing upstart files to: /etc/init/")
  message(STATUS "Installing logrotate config to: /etc/logrotate.d/percona-proxy-logrotate")
endif()
