if(PACKAGE AND TARBALL)
  set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
  set(CMAKE_INSTALL_RPATH "$ORIGIN/../${CMAKE_INSTALL_LIBDIR}/percona-proxy" CACHE PATH "" FORCE)
else()
  set(CMAKE_INSTALL_RPATH ${CMAKE_INSTALL_RPATH};${CMAKE_INSTALL_PREFIX}/${PERCONA_PROXY_LIBDIR})
endif()


